# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8450-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ferrarri ovaltine udon wly,$(TARGET_DEVICE)),)

endif
